node {
  def commit_id
  stage('preparation') {
    checkout scm
    sh 'git rev-parse --short HEAD > .git/commit-id'
    commit_id = readFile('.git/commit-id').trim()
  }
  stage('test') {
    nodejs(nodeJSInstallationName: 'node') {
      sh 'npm install'
      sh 'npm run test'
    }
  }
  stage('docker build/push') {
    docker.withRegistry('https://index.docker.io/v2/', 'dockerhub' /* id of credential */) {
      def app = docker.build('wtchrs/docker-nodejs-example:${commit_id}', '.' /* path to build */).push()
    }
  }
}